export const RESTAURANTS = {
  GET_RESTAURANTS_LOADING: 'GET_RESTAURANTS_LOADING',
  GET_RESTAURANTS_SUCCESS: 'GET_RESTAURANTS_SUCCESS',
  GET_RESTAURANTS_FAILURE: 'GET_RESTAURANTS_FAILURE'
};

export const FILTER = {
  SET_VISIBILITY_FILTER: 'FILTER_RESTAURANTS'
};